## Test configuration name. Used for reporting.
name: Network and HTTP screwer.

## Test Description. Used for reporting
description: Slow network to mobile levels, and add 1s delay to all messages

## Specify log output level
##
## Log Levels supported:
## Trace (0), Debug (1), Info (2, Default), Warn (3), Error (4), Fatal (5)
loglevel: 1

## Configure a proxy that will handle your requests, and forward
## to proxied host.
##
## Currently supports `tcp_proxy` and `http_proxy`.
proxy:
  ## HTTP Proxy: Configures an HTTP Proxy
  ##
  ## NOTE: SSL is currently not supported
  - name: http_proxy
    config:
      host: localhost
      port: 8181
      protocol: http
      proxy_host: l.com
      proxy_port: 443
      proxy_protocol: https
      http_proxy: test.com:82
      insecure: true
      proxy_rules:
        - request:
            method: .*
            host: .*
            path: /
          pass:
            stub_proxy:
              stub_body: "hello world"
              stub_status: 500
              stub: true



## Middleware
##
## Middleware are plugins that are given the opportunity to intervene
## before a request is dispatched to the proxied system (PRE_DISPATCH event)
## and afterwards (POST_DISPATCH event). They are given a reference to
## the current context (HTTP Context or []bytes) and can mutate them.
##
## Middleware are executed in the order specified in this config.
##
middleware:
  - name: delay
    config:
      request_delay:  100                 # Delay in ms to apply to request
      response_delay: 500                 # Delay in ms to apply to response
